### ISSUE TITLE
Images for build documentation & equipment list

### ISSUE THREAD

**Issue by jtanadi** [andyclymer/minikbd#3]
Hi! I've been wanting to tinker with hardware for a little while, so this is great.

Couple of things I'm curious about are if you have more images for the build documentation (because I'm afraid of screwing things up) and if you have a recommended equipments list of some sort. I haven't done a lot of (any) builds, so curious about what equipments to start with, etc.

Thanks!

**Comment by andyclymer** [comment]
Hi @jtanadi 

I do have some step-by-step photos that I took of a recent build, I'll add them to the build docs and let you know by way of this issue once they're all there.

As for the part list, I have part numbers and a buying guide here:
https://github.com/andyclymer/minikbd/blob/master/Hardware/PartsList.md

If you want to build the configuration with the rotary encoders then all of the parts can be purchased conveniently from Adafruit, otherwise there are many options for ordering keyboard keyswitches and keycaps. I like using the low profile keyswitches from Novel Keys which I link to on the [Parts List](https://github.com/andyclymer/minikbd/blob/master/Hardware/PartsList.md) page. Let me know however if anything is unclear with the buying guide for parts.

**Comment by jtanadi** [comment]
Thanks, can't wait to see those photos!

I was looking more for equipments, instead of parts—eg. what kind of soldering iron, solder, etc. if you have any recommendations.

**Comment by andyclymer** [comment]
Hi @jtanadi 

I added a few more photos to the build docs, here's one as an example:
https://github.com/andyclymer/minikbd/blob/master/Hardware/Build-SixKeyswitches.md

If you're already going to be ordering a Trinket M0, I think you can trust the soldering irons that Adafruit sells on their own site. If you're new to electronics, pick up a small prototyping breadboard and a starter kit with a few small buttons and sensors. After you're done learning how it works you can attach it to a MiniKbd circuit board.

Andy

**Comment by jtanadi** [comment]
Amazing. Thanks so much!
